### ISSUE TITLE
is project dead?

### ISSUE THREAD

**Issue by themnd** [couchbaselabs/ansible-couchbase-server#14]
the latest commit is almost one year old and there is a pull request not being processed.
Is this repo dead?
Is there any maintainer?

**Comment by tleyden** [comment]
hey @themnd 

Looks like Brian has left Couchbase, and he was the maintainer.

On my team at Couchbase we use ansible heavily, but we've been maintaining our own scripts in the [mobile-testkit](https://github.com/couchbaselabs/mobile-testkit) repo.  At some point, it would be nice to consume the ansible work in this repo rather than duplicate it.

I will ask around to see who might be available to help maintain/support this repo

Gonna close this issue since there are no tangible action items, but feel free to continue the conversation here
